language: haskell
install:
  - npm install -g elm
  - elm-package install -y
before_script: 
#  - elm-make --yes --output test.js test/Tests.elm
#  - elm test init
#script: node test.js
script: elm test

# whitelist
branches: 
  only: 
    - gh-pages
    - /.*/

